-- Wild Oasis schema (matches the Ultimate React Course)
-- Run this in Supabase → SQL Editor.
-- Column names use camelCase (quoted identifiers) — the app expects this.
--
-- If you already created snake_case tables, drop them first:
--   drop table if exists bookings cascade;
--   drop table if exists guests cascade;
--   drop table if exists cabins cascade;
--   drop table if exists settings cascade;

-- ─── Storage buckets (create in Dashboard → Storage if not present) ───
-- cabin-images (public)
-- avatars (public)

-- ─── Cabins ───────────────────────────────────────────────────────────
create table if not exists cabins (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  name text not null,
  "maxCapacity" int not null,
  "regularPrice" numeric not null,
  discount numeric not null default 0,
  image text not null,
  description text not null default ''
);

-- ─── Guests ───────────────────────────────────────────────────────────
create table if not exists guests (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  "fullName" text not null,
  email text not null,
  nationality text not null,
  "nationalID" text not null,
  "countryFlag" text not null
);

-- ─── Bookings ─────────────────────────────────────────────────────────
create table if not exists bookings (
  id bigint generated always as identity primary key,
  created_at timestamptz default now() not null,
  "startDate" date not null,
  "endDate" date not null,
  "numNights" int not null,
  "numGuests" int not null,
  "cabinPrice" numeric not null,
  "extrasPrice" numeric not null,
  "totalPrice" numeric not null,
  status text not null,
  "hasBreakfast" boolean not null default false,
  "isPaid" boolean not null default false,
  observations text default '',
  "cabinId" bigint references cabins(id) on delete cascade not null,
  "guestId" bigint references guests(id) on delete cascade not null
);

-- ─── Settings (single row, id = 1) ────────────────────────────────────
create table if not exists settings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  "minBookingLength" int not null default 3,
  "maxBookingLength" int not null default 30,
  "maxGuestsPerBooking" int not null default 10,
  "breakFastPrice" numeric not null default 15
);

insert into settings (
  "minBookingLength",
  "maxBookingLength",
  "maxGuestsPerBooking",
  "breakFastPrice"
)
values (3, 30, 10, 15);

-- ─── Row Level Security (enable + policies from the course) ───────────
alter table cabins enable row level security;
alter table guests enable row level security;
alter table bookings enable row level security;
alter table settings enable row level security;

create policy "Cabins are viewable by authenticated users"
  on cabins for select to authenticated using (true);

create policy "Cabins are insertable by authenticated users"
  on cabins for insert to authenticated with check (true);

create policy "Cabins are updatable by authenticated users"
  on cabins for update to authenticated using (true);

create policy "Cabins are deletable by authenticated users"
  on cabins for delete to authenticated using (true);

create policy "Guests are viewable by authenticated users"
  on guests for select to authenticated using (true);

create policy "Guests are insertable by authenticated users"
  on guests for insert to authenticated with check (true);

create policy "Guests are updatable by authenticated users"
  on guests for update to authenticated using (true);

create policy "Bookings are viewable by authenticated users"
  on bookings for select to authenticated using (true);

create policy "Bookings are insertable by authenticated users"
  on bookings for insert to authenticated with check (true);

create policy "Bookings are updatable by authenticated users"
  on bookings for update to authenticated using (true);

create policy "Bookings are deletable by authenticated users"
  on bookings for delete to authenticated using (true);

create policy "Settings are viewable by authenticated users"
  on settings for select to authenticated using (true);

create policy "Settings are updatable by authenticated users"
  on settings for update to authenticated using (true);
